### ISSUE TITLE
Erreur sur la prise en compte du démantellement nucléaire et de la fin de vie des centrales

### ISSUE THREAD

**Issue by rmontfort** [AirLoren/airloren.github.io#2]
Merci pour cette critique argumentée.
Je suis globalement d'accord avec l'essentiel des points soulevés, mais un point sur la fin de vie nucléaire me semble inexact, lors que vous écrivez : "_Il manque forcément une évaluation précise de la fin de vie puisque pour mesurer l’impact carbone du démantèlement d’une centrale nucléaire, il faudrait avoir terminé au moins un démantèlement._"

C'est doublement faux:

- D'abord parce que plusieurs réacteurs de design identique ou similaire à ceux du parc français ont déjà été complètement démentelés. Le meilleur exemple et le plus documenté est celui de Maine Yankee, aux Etats-Unis : https://fr.wikipedia.org/wiki/Centrale_nucl%C3%A9aire_de_Maine_Yankee C'est d'ailleurs une des études de cas qui a été utilisée par EDF pour chiffrer les coûts et implications des démentèlements à venir sur le parc français, 
- Ensuite parce que le FE français de 6g/kWh pour le nucléaire inclut bien la fin de vie des centrales, en s'appuyant sur l'étude ACV de cette publication : https://www.sciencedirect.com/science/article/pii/S0360544214002035?via%3Dihub
Un interlocuteur de l'ADEME a confirmé ce point en 2019 ici : https://bilans-ges.ademe.fr/forum/viewtopic.php?f=19&t=4089&p=4560&hilit=nucl%C3%A9aire&sid=60c58ebf9f8f03c2b50e0ec50632c2ca#p4558

Bonne continuation.

**Comment by AirLoren** [comment]
Merci pour ce retour.
Je me souviens avoir lu des études qui disaient l'inverse mais comme je ne les retrouve pas, je ne peux qu'admettre que vous avez certainement raison car vos sources semblent fiables.
Je vais donc corriger.
Sinon, n'étant pas du tout compétent sur le sujet, pour ma culture personnelle, j'aimerais savoir si on peut considérer que l'impact du démentèlement de 2 centrales ayant des designs similaires sera lui aussi similaire? Autrement dit, les spécificités (principalement la localisation géographique et la réglementation locale) ont elles un impact négligeable?

**Comment by AirLoren** [comment]
Erratum publié.
Encore merci pour les précisions et si vous savez répondre à ma question ci-dessus, cela m'interesse vraiment.

**Comment by rmontfort** [comment]
Bonjour,
Je ne suis pas expert nucléaire, juste passionné des questions énergétiques. J'imagine qu'il doit tout de même y avoir des variations à prendre en compte du fait de la localisation et de la réglementation, notamment en ce qui concerne les précautions à prendre durant les opérations de décommissionnement, les normes de sécurité qui s'appliquent, les obligations de traitement des déchets produits etc. 
Cela dit, je ne pense pas (mais il s'agit d'une conviction, pas d'un argumentaire factuel) qu'entre deux pays de niveaux de développement comparables, avec des parcs électro-nucléaires de taille significative (95 réacteurs aux USA, 56 en France) à la fiabilité reconnue et disposant d'un organe de contrôle indépendant (Nuclear Regulatory Commission aux USA, Autorité de sûreté nucléaire en France), les exigences doivent être proches et les impacts associés également.
J'ai peut être quelques noms dans mon réseau à vous recommander si vous souhaitez creuser davantage la question, faites moi un message privé le cas échéant.
