### ISSUE TITLE
Intéressant

### ISSUE THREAD

**Issue by priximmo** [AirLoren/airloren.github.io#3]
Merci pour ce travail réalisé. On sent le passionné qui travaille bien son sujet. 

Ce talk m'a profondément agacé car les interlocuteurs sont d'importants influenceurs dans notre secteur et peuvent donner l'impression que les personnes travaillant dans le numérique pensent cela.

Après avoir évoqué de nombreuses fois ces sujets sur ma petite chaîne youtube, je m'aperçois qu'heureusement nous ne sommes pas seuls. C'est un peu dur de le dire mais j'ai comme une impression d'une chape de plomb et les gens m'ont avoué que j'étais courageux d'aborder ces sujets... pourtant il n'y a pas lieu d'en arriver là compte tenu des enjeux.

Bref merci. Je serai vraiment heureux de pouvoir échanger avec vous sur ces sujets et pourquoi pas parler de boavizta ou présenter votre travail sur ma chaine.

Merci

**Comment by AirLoren** [comment]
Merci Xavier. Ce genre de retour nous fait bien plaisir.
Je te recontacte rapidement pour en discuter.
